### ISSUE TITLE
Uncaught (in promise) DOMException - bad video perfomance

### ISSUE THREAD

**Issue by justerror** [flussonic/mse-player#13]
I followed the [documentation](https://erlyvideo.ru/doc/proigryvanie/mse-player).

The `play()` method call leads to an error `Uncaught (in promise) DOMException` in latest Chrome browser ([explanation](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)).

Seem to be Chrome browser does not use hardware acceleration in this case.
With this violation video is played but skipped frames and lags (about 0.5-1 frame per second). 

**Quick solution: add `muted` attribute to `<video>`**

it would be nice to designate this in the example in the documentation, so that users would not have a negative first experience.

**Comment by zamarawka** [comment]
Docs remind you about autoplay policy, so you can handle this case by your self.
