### ISSUE TITLE
Return to nowhere. Autoplay exception bubbling is broken.

### ISSUE THREAD

**Issue by zamarawka** [flussonic/mse-player#15]
https://github.com/flussonic/mse-player/blob/b6993c575526118a01e225ddbdab306559180ce2/src/modules/MsePlayer.external.js#L320

Return from Promise executor has no effect.

**Comment by maxlapshin** [comment]
Seems to be fixed in  6d98a9a218adf8d9

**Comment by maxlapshin** [comment]
@zamarawka is it ok now?
