### ISSUE TITLE
Error Playing websocket

### ISSUE THREAD

**Issue by willowTank** [flussonic/mse-player#9]
![image](https://user-images.githubusercontent.com/24641385/50323293-46938c80-04d9-11e9-86d7-91e65930f801.png)
Please look at this image.
I just got this error.
Please help me

**Comment by otmjka** [comment]
Hello @willowTank 

Can you provide more information?
- stream config
- launch the MsePlayer with `debug: true` flag. And send all logs when error occurs.

**Comment by willowTank** [comment]
Thank for your guild (:like)
